return {
	-- === OWNER (3) ===
	{ Name = "wino444", Rank = 3 },
	{ Name = "ojhvhknhj", Rank = 3 },
	{ Name = "jgjkjgj4", Rank = 3 },
	
	-- === VIP (2) ===
	{ Name = "Toonyaganx2", Rank = 2 },
	{ Name = "birdV3_123", Rank = 2 },
	{ Name = "hgjhhjjg4", Rank = 2 },
	{ Name = "Ddbcvc97", Rank = 2 },
	{ Name = "Nadbubna27936", Rank = 2 },
	{ Name = "HRdrluOs1416", Rank = 2 },
	{ Name = "STOPMNJTVV", Rank = 2 },
	{ Name = "Heedoor9995", Rank = 2 },
	{ Name = "moszaa13340", Rank = 2 },
	{ Name = "maidjab1_174", Rank = 2 },
	{ Name = "Margarite218188", Rank = 2 },
	{ Name = "Libbyeli1091", Rank = 2 },
	{ Name = "odododoo2", Rank = 2 },
	{ Name = "MiNiKaiYungShop89989", Rank = 2 },
	{ Name = "zx71828", Rank = 2 },
	{ Name = "Thai123456a1", Rank = 2 },
	{ Name = "RefK0n1_0056", Rank = 2 },
	{ Name = "TBFDEL0", Rank = 2 },
	{ Name = "ZER3H", Rank = 2 },
	{ Name = "Mopizxcd", Rank = 2 },
	{ Name = "SUN_lGG65", Rank = 2 },
	{ Name = "kazagaki159", Rank = 2 },
	{ Name = "zzxxccvv0336", Rank = 2 },
	{ Name = "burnserika", Rank = 2 },
	{ Name = "BanBlow", Rank = 2 },
	{ Name = "Pookiekub0", Rank = 2 },
	{ Name = "pro_exploiter", Rank = 2 },
}
